# numpy practice

In [1]:
#pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
#import this library in j.note book
import numpy as np

# Creating an array using numpy

In [4]:
food = np.array(["samosa", "pakora", "raita"])
food

array(['samosa', 'pakora', 'raita'], dtype='<U6')

In [5]:
price = np.array([5, 5, 5])
price

array([5, 5, 5])

In [6]:
type(price)

numpy.ndarray

In [7]:
type(food)

numpy.ndarray

In [8]:
len(price)

3

In [9]:
len(food)

3

In [10]:
price [0]

5

In [11]:
price [1]

5

In [12]:
price [2]

5

In [13]:
food [0]

'samosa'

In [14]:
food [1]

'pakora'

In [15]:
food [2]

'raita'

In [16]:
price.mean()

5.0

In [17]:
#zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [18]:
#empty
np.empty(5)

array([0., 0., 0., 0., 0.])

In [19]:
#ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [20]:
#arange
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
#specify
np.arange(2, 20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [22]:
#specific interval
np.arange(2, 20, 2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [23]:
#Table of 5
np.arange(5, 55, 5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [24]:
np.linspace(1, 10, num=5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [25]:
#specify data type
np.ones(50,  dtype=np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1], dtype=int64)

In [26]:
np.ones(50,  dtype=np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# array function

In [27]:
a = np.array([10, 12, 15, 2, 5, 6, 100, 320, 0, 5, 10, 3])
a

array([ 10,  12,  15,   2,   5,   6, 100, 320,   0,   5,  10,   3])

In [28]:
a.sort()
a

array([  0,   2,   3,   5,   5,   6,  10,  10,  12,  15, 100, 320])

In [29]:
b = np.array([10.2, 3.3, 53.6, 81.6, 65.5])
b

array([10.2,  3.3, 53.6, 81.6, 65.5])

In [30]:
c = np.concatenate((a,b))
c

array([  0. ,   2. ,   3. ,   5. ,   5. ,   6. ,  10. ,  10. ,  12. ,
        15. , 100. , 320. ,  10.2,   3.3,  53.6,  81.6,  65.5])

In [31]:
c.sort()
c

array([  0. ,   2. ,   3. ,   3.3,   5. ,   5. ,   6. ,  10. ,  10. ,
        10.2,  12. ,  15. ,  53.6,  65.5,  81.6, 100. , 320. ])

# 2-D  array

In [32]:
x = np.array([[1,2], [5,6]])

In [33]:
y = np.array([[8,3], [3,1]])

In [34]:
np.concatenate((x,y), axis=0) 

array([[1, 2],
       [5, 6],
       [8, 3],
       [3, 1]])

In [35]:
np.concatenate((x,y), axis=1) 

array([[1, 2, 8, 3],
       [5, 6, 3, 1]])

In [43]:
a = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [42]:
#To find the number of dimensions of the array
a.ndim

3

In [44]:
#To find the total number of elements 
a.size

24

In [45]:
#to find the shape 
a.shape

(3, 2, 4)

In [46]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [47]:
# reshape
b = a.reshape(3, 2)
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [48]:
#reshape
np.reshape(a, newshape=(1, 6), order='C')

array([[0, 1, 2, 3, 4, 5]])

In [50]:
#convert a 1D array into a 2D array
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [51]:
a.shape

(6,)

In [52]:
# row wise
b = a[np.newaxis, :]
b

array([[1, 2, 3, 4, 5, 6]])

In [53]:
b.shape

(1, 6)

In [54]:
# column wise
b = a[:, np.newaxis]
b

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [55]:
b.shape

(6, 1)

In [56]:
a

array([1, 2, 3, 4, 5, 6])

In [57]:
a [2:6]


array([3, 4, 5, 6])

In [58]:
a*6

array([ 6, 12, 18, 24, 30, 36])

In [59]:
a.sum()

21

In [60]:
a.mean()

3.5